// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Book struct {
	ID        int64
	CreatedAt int64
	UpdatedAt int64
	Title     string
	Author    string
	Genre     string
	Ratting   int64
}

type LoanedBook struct {
	ID        int64
	CreatedAt int64
	UpdatedAt int64
	Date      int64
	Name      string
	BookID    int64
}
