Website = "https://github.com/dubbersthehoser/mayble"

[Details]
  Icon = "Icon.png"
  Name = "mayble"
  ID = "com.dubbersthehoser.mayble"
  Version = "2.0.0"
  Build = 27

[LinuxAndBSD]
  GenericName = "Book Management"
  Categories = ["Office", "Database"]
  Keywords = ["books", "office"]
