// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Book struct {
	ID        int64
	CreatedAt int64
	UpdatedAt int64
	Title     string
	Author    string
	Genre     string
}

type LoanedBook struct {
	CreatedAt int64
	UpdatedAt int64
	Date      string
	Name      string
	BookID    int64
}

type ReadBook struct {
	CreatedAt     int64
	UpdatedAt     int64
	Rating        int64
	DateCompleted string
	BookID        int64
}
