// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: read.sql

package database

import (
	"context"
)

const createRead = `-- name: CreateRead :one
INSERT INTO read_books(created_at, updated_at, rating, date_completed, book_id)
VALUES (
	unixepoch(),
	unixepoch(),
	?,
	?,
	?
)
RETURNING created_at, updated_at, rating, date_completed, book_id
`

type CreateReadParams struct {
	Rating        int64
	DateCompleted string
	BookID        int64
}

func (q *Queries) CreateRead(ctx context.Context, arg CreateReadParams) (ReadBook, error) {
	row := q.db.QueryRowContext(ctx, createRead, arg.Rating, arg.DateCompleted, arg.BookID)
	var i ReadBook
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
		&i.DateCompleted,
		&i.BookID,
	)
	return i, err
}

const deleteRead = `-- name: DeleteRead :exec
DELETE FROM read_books WHERE book_id = ?
`

func (q *Queries) DeleteRead(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRead, bookID)
	return err
}

const getReadByBookID = `-- name: GetReadByBookID :one
SELECT rating, date_completed, book_id FROM read_books
WHERE book_id = ?
`

type GetReadByBookIDRow struct {
	Rating        int64
	DateCompleted string
	BookID        int64
}

func (q *Queries) GetReadByBookID(ctx context.Context, bookID int64) (GetReadByBookIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReadByBookID, bookID)
	var i GetReadByBookIDRow
	err := row.Scan(&i.Rating, &i.DateCompleted, &i.BookID)
	return i, err
}

const updateRead = `-- name: UpdateRead :one
UPDATE read_books
SET
	updated_at = unixepoch(),
	rating = ?,
	date_completed = ?
WHERE book_id = ?
RETURNING created_at, updated_at, rating, date_completed, book_id
`

type UpdateReadParams struct {
	Rating        int64
	DateCompleted string
	BookID        int64
}

func (q *Queries) UpdateRead(ctx context.Context, arg UpdateReadParams) (ReadBook, error) {
	row := q.db.QueryRowContext(ctx, updateRead, arg.Rating, arg.DateCompleted, arg.BookID)
	var i ReadBook
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
		&i.DateCompleted,
		&i.BookID,
	)
	return i, err
}
