name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix: 
        include:
          - arch: amd64
            os: linux
            runner: ubuntu-latest
            ext: tar.xz

          - arch: arm64
            os: linux
            ext: tar.xz
            runner: ubuntu-latest

          - arch: amd64
            os: windows
            ext: exe
            runner: windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Install Fyne Cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Build (${{ matrix.os }}/${{ matrix.arch }})
        if: ${{ matrix.os != windows }}
        run: fyne-cross ${{ matrix.os }} -release -arch=${{ matrix.arch }} -name mayble_${{ matrix.os }}_${{ matrix.arch }}
        if: ${{ matrix.os == windows }}
        run: fyne-cross ${{ matrix.os }} -release -name mayble_${{ matrix.os }}_${{ matrix.arch }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os}}-${{ matrix.arch }}
          path: fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}/*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Linux amd64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64-dist
          path: dist/amd64

      - name: Download Windows amd64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-amd64-dist
          path: dist/amd64

      - name: Download arm64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-dist
          path: dist/arm64

      - name: Create Github Release and Upload Binaries
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            dist/amd64/*
            dist/arm64/*
          generateReleaseNotes: true
