name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix: 
        include:
          - arch: amd64
            os: linux
            runner: ubuntu-latest
            exec: "fyne-cross linux -release -arch amd64 -name mayble_linux_amd64"
            dist: "fyne-cross/dist/linux-amd64"
            upload: "fyne-cross/dist/linux-amd64/*"

          - arch: arm64
            os: linux
            runner: ubuntu-latest
            exec: "fyne-cross linux -release -arch arm64 -name mayble_linux_arm64"
            dist: "fyne-cross/dist/linux-arm64"
            upload: "fyne-cross/dist/linux-arm64/*" 

          - arch: amd64
            os: windows
            runner: windows-latest
            exec: "fyne -os windows -name mayble_windows_amd64"
            upload: "mayble_windows_amd64.exe"

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Install Fyne Tool
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Install Fyne Cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Build (${{ matrix.os }}/${{ matrix.arch }})
        run: ${{ matrix.exec }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os}}-${{ matrix.arch }}
          path: ${{ matrix.upload }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Linux amd64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64
          path: dist/

      - name: Download Linux arm64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: dist/

      - name: Download Windows amd64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-amd64
          path: dist/


      - name: Create Github Release and Upload Binaries
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: dist/*
          generateReleaseNotes: true
