name: release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] 
        #architecture: [amd64, arm64]
        architecture: [amd64]

    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
      
      - name: Install fyne Tool
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Install Fyne Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev libxkbcommon-dev

      - name: Package Linux
        run: |
          fyne package
          mv mayble.tar.xz mayble-${{ matrix.os }}-${{ matrix.architecture }}_${{ github.ref_name }}.tar.xz

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: mayble-*-*_*.tar.xz
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

