name: release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
      
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Package Linux AMD64
        run: fyne-cross linux -arch amd64
      
      - name: Package Linux ARM64
        run: fyne-cross linux -arch arm64
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: fyne-cross/dist/linux-*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

